### ISSUE TITLE
Single-header version

### ISSUE THREAD

**Issue by martinfinke** [cbeck88/strict-variant#6]
Hi, thanks for this great project! I've been looking for something like this 🙂 `std::variant` IMO violates C++'s "don't pay for what you don't use" principle (e.g. lots of `valueless_by_exception` checks) and doesn't fit my projects.

**Would it be possible to create a single-header version?** I can concatenate the files myself, but it would be nice to have it automatically generated when there's a new release.

[EDIT] Just wanted to add that I get about 35% better overall performance in my benchmarks, compared to `mpark::variant`. This is great 👍

**Comment by cbeck88** [comment]
Hey, thanks for your interest :)

The only reason I can think not to do that is that there are some headers that add "optional" stuff that you might not want.

For instance `variant/stream_ops.hpp` makes variant streamable into `std::ostream`'s. Not everyone wants that though, I've seen a lot of libraries where that kind of thing is in a separate header to make it opt in.

The other big one that comes to mind is `variant/spirit.hpp`. The library has no dependency on boost spirit, but if you want to make boost spirit grammars that parse directly into your data structures and use `strict_variant` in your data structures, you need to specialize this trait that tells spirit that this thing is a variant and how to use it. I already did that work but I doubt you want to include that in all your translation units because then you will be compiling a bunch of boost spirit stuff you don't need -- boost spirit can take a long time esp. on older compilers. Usually what I do is only include `variant/spirit.hpp` in the `.cpp` file where I am actually using spirit. If you jam this in single header used everywhere it might hurt the build time of your project.

But yeah I guess for many new / small projects that have fine build times it doesn't really matter.

Do you already have a script to concatenate the files? If not I guess I can throw one together.

**Comment by martinfinke** [comment]
Good points! I don't want to use the iostream or boost::spirit functionality, just everything I would get if I include variant.hpp.

I've [created a script](https://gist.github.com/martinfinke/c474ac992155f29f0f0d871ddd8cd99d) that does this. To use it on strict-variant, run this from the main repository folder:

```bash
create_single_header.py include/strict_variant/variant.hpp --header_search_paths include --ignored_headers path/to/stream_ops.hpp path/to/spirit.hpp -o strict_variant.h
```

Actually the `--ignored_headers` isn't needed in this case, because stream_ops.hpp and spirit.hpp aren't #included from variant.hpp, but it's an FYI in case you would like to create something more custom.
Note: For `--ignored_headers`, the paths have to be exactly as they appear in #includes. This could be changed to be more flexible, but I personally don't need that right now.
